name: Main CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v3

      - name: Create/Update systemd service
        run: |
          SERVICE_FILE="/etc/systemd/system/${REPO_NAME}.service"
          TEMPLATE_FILE="$GITHUB_WORKSPACE/.github/deploy/systemd.service"
          envsubst < $TEMPLATE_FILE | sudo tee $SERVICE_FILE

          sudo systemctl daemon-reload
          sudo systemctl enable ${REPO_NAME}.service

      - name: Start/Restart systemd service
        run: |
          sudo systemctl restart ${REPO_NAME}.service
